In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#中文文字显示问题
from pylab import mpl
# 指定默认字体
mpl.rcParams['font.sans-serif'] = ['FangSong'] 
# 解决保存图像是负号'-'显示为方块的问题
mpl.rcParams['axes.unicode_minus'] = False 
from sklearn.decomposition import PCA
df_org = pd.read_excel('Data.xlsx',index_col='Date').iloc[:, 1:]

In [2]:
df_org

,Volume,Corn,S&P500,VIX,DI,DR,BTU,UNG,Total Deaths,Total Cases
Date,,,,,,,,,,
2020-01-23,43330,393.75,3325.540039,12.980000,97.690002,61.877998,7.620000,14.940000,0,1
2020-01-24,43263,387.25,3295.469971,14.560000,97.849998,61.892799,7.470000,14.610000,0,2
2020-01-27,39367,380.50,3243.629883,18.230000,97.959999,62.131001,7.460000,14.640000,0,3
2020-01-28,41537,386.50,3276.239990,16.280001,98.019997,62.893902,6.950000,14.900000,0,3
2020-01-29,21453,384.25,3273.399902,16.389999,97.989998,62.213299,6.920000,14.660000,0,3
...,...,...,...,...,...,...,...,...,...,...
2022-03-31,31,748.75,4530.410156,20.559999,98.309998,81.714996,24.530001,19.719999,978605,79953815
2022-04-04,18406,750.50,4582.640137,18.570000,98.989998,83.714996,24.990000,20.049999,979805,80034180
2022-04-05,15613,759.75,4525.120117,21.030001,99.470001,83.964996,24.780001,21.059999,980343,80067830
2022-04-06,20212,756.50,4481.149902,22.100000,99.599998,82.089996,25.129999,21.230000,981285,80111083
2022-04-07,19577,757.75,4500.209961,21.549999,99.750000,79.214996,27.150000,22.370001,981803,80146430

In [5]:
df_std = (df_org - df_org.mean())/df_org.std()
df_corr = df_std.corr()
eig_value,eig_vector=np.linalg.eig(df_corr)
#特征值

#特征值排序
eig=pd.DataFrame({"eig_value":eig_value})
eig=eig.sort_values(by=["eig_value"], ascending=False) 
#获取累积贡献度
eig["eig_cum"] = (eig["eig_value"]/eig["eig_value"].sum()).cumsum()
#合并入特征向量
eig=eig.merge(pd.DataFrame(eig_vector).T, left_index=True, right_index=True)
eig.to_csv('ceig.csv')

In [6]:
eig

,eig_value,eig_cum,0,1,2,3,4,5,6,7,8,9
0,5.082427,0.508243,-0.008564,0.400316,0.409670,-0.217847,-0.051777,0.208584,0.384315,0.249430,0.430695,0.427537
1,2.006631,0.708906,-0.066014,0.114921,0.216863,-0.455762,-0.626318,-0.295652,-0.273651,-0.407082,0.062048,-0.059589
2,1.092499,0.818156,0.754805,-0.083456,0.104992,-0.166977,0.066801,-0.518862,0.093217,0.311589,-0.036298,-0.060207
3,0.923817,0.910537,-0.619608,-0.234834,0.065304,-0.380698,0.208374,-0.429111,0.162317,0.376497,-0.090034,-0.089358
4,0.360484,0.946586,0.175995,-0.216433,-0.115690,-0.592857,-0.118294,0.613808,0.110780,0.173883,-0.245129,-0.252922
5,0.294946,0.976080,0.088358,0.121851,0.028181,-0.407204,0.703939,-0.017417,-0.063485,-0.547945,0.023010,0.100498
6,0.123764,0.988457,0.045436,-0.737700,0.330155,0.021656,0.047731,0.135838,-0.349444,0.008991,0.343712,0.288448
7,0.074946,0.995951,-0.025606,0.397401,0.077232,-0.079543,0.173763,0.098645,-0.766040,0.439018,0.015162,-0.097035
8,0.033919,0.999343,0.019683,-0.019896,-0.701557,-0.207708,-0.120085,-0.097956,-0.123943,0.099412,0.028594,0.643284
9,0.006567,1.000000,-0.005979,0.014557,0.385390,0.069119,-0.027332,0.029787,-0.042291,-0.007207,-0.788305,0.470692